name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v2
        
      - name: Echo
        run: echo "otp"
